# dataset infomation
dataset_name: mimic_cxr
image_dir: data/mimic/dataset/images/files
json_report: data/mimic/dataset/ann_history_entity.json
knowledge_file: data/mimic/dataset/entity2knowledge_entity2id.json
pretrained_embedding: data/mimic/dataset/knowledge_entity2embedding.npy

# RadGraph使用entity_file和relation_file
entity_file: data/mimic/dataset/Certified/Certified_RotatE_entity.npy
relation_file: data/mimic/dataset/Certified/Certified_RotatE_relation_feat.npy

N: 1

# training parameter
test_steps: 30000

# Hyperparameter
#max_seq_length: 100
#num_labels: 14
#threshold: 10 #3
max_seq_length: 80
num_labels: 14
threshold: 3

batch_size: 64
epochs: 30

step_size: 5

num_layers: 3

gamma: 0.5
seed: 456789
lr_ed: 0.0005

label_smoothing: 0.1

# Visual Extractor
# d_vf:
# efficientnet: 1280
# densenet: 1024
# resnet101: 2048
visual_extractor: resnet101
pretrain_cnn_file:
d_vf: 2048

# Output Dir
save_dir: results