# dataset infomation
dataset_name: iu_xray
image_dir: data/iu/r2gen_split/images_normalized
json_report: data/iu/r2gen_split/idx2caption.json
pair_split: data/iu/r2gen_split/pair_list.csv

# 知识图谱的参数名不同，不冲突
# 之前自己提取的知识图谱使用graph_path参数
graph_path: data/MIMIC_KG_RotatE_entity.npy
# RadGraph使用entity_file和relation_file
entity_file: data/RadGraph/RadGraph_MIMIC_KG_FromTrainSet_RotatE_entity.npy
relation_file: data/RadGraph/RadGraph_MIMIC_KG_FromTrainSet_RotatE_relation.npy

N: 1

# Hyperparameter
max_seq_length: 60
num_labels: 14
threshold: 3

batch_size: 64
epochs: 50
step_size: 20

num_layers: 3

gamma: 0.1
seed: 9223
lr_ed: 0.0005

# Visual Extractor
# d_vf:
# efficientnet: 1280
# densenet: 1024
# resnet101: 2048
visual_extractor: resnet101
pretrain_cnn_file:
d_vf: 2048

# Output Dir
save_dir: results/RadModel
