# dataset infomation
dataset_name: mimic_cxr
image_dir:
json_report:
pair_split:

# 知识图谱的参数名不同，不冲突
# 之前自己提取的知识图谱使用graph_path参数
graph_path: data/MIMIC_KG_RotatE_entity.npy
# RadGraph使用entity_file和relation_file
entity_file: data/RadGraph/RadGraph_MIMIC_KG_FromTrainSet_RotatE_entity.npy
relation_file: data/RadGraph/RadGraph_MIMIC_KG_FromTrainSet_RotatE_relation.npy

N: 1

# training parameter
test_steps: 30000

# Hyperparameter
#max_seq_length: 100
#num_labels: 14
#threshold: 10 #3
max_seq_length: 80
num_labels: 14
threshold: 3

batch_size: 64
epochs: 30

step_size: 5

num_layers: 3

gamma: 0.5
seed: 456789
lr_ed: 0.0005

label_smoothing: 0.1

# Visual Extractor
# d_vf:
# efficientnet: 1280
# densenet: 1024
# resnet101: 2048
visual_extractor: resnet101
pretrain_cnn_file:
d_vf: 2048

# Output Dir
save_dir: results/RadModel